name: "Christopher's Blog"
favicon: null
layout_spectrum: 0.34474
typography_spectrum: 0.17772
title: This is a pretend site for my blog.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6eef1'
    - '#000308'
    - '#abc6d3'
    - '#819daa'
    - '#2b3c47'
  brandStrength: 0.125
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
