name: "Christopher's Blog"
favicon: null
layout_spectrum: 0.85226
typography_spectrum: 0.4248
title: This is a pretend site for my blog.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#0d0f0c'
    - '#aac7de'
    - '#4b7fa4'
    - '#194f69'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
