name: "Christopher's Blog"
favicon: null
layout_spectrum: 0.18781
typography_spectrum: 0.29124
title: This is a pretend site for my blog.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b2bcb3'
    - '#5e807c'
    - '#043a2e'
    - '#bfdfce'
    - '#000d0d'
  brandStrength: 0.125
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
