name: "Christopher's Blog"
favicon: null
layout_spectrum: 0.53108
typography_spectrum: 0.40578151238150895
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5668850364163518
  lightness: 0.222242173505947
  saturation: 0.042475361842662096
  rhythmicContrast: 0.8196461300831288
purpose: []
