name: "Christopher's Blog"
favicon: null
layout_spectrum: 0.13087
typography_spectrum: 0.33834
title: This is a pretend site for my blog.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000327'
    - '#91add2'
    - '#182e5e'
    - '#d1d0d8'
    - '#32589d'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
