name: "Christopher's Blog"
favicon: null
layout_spectrum: 0.71703
typography_spectrum: 0.17772
title: This is a pretend site for my blog.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050d0f'
    - '#d2d8e5'
    - '#6eafd0'
    - '#485a61'
    - '#37342d'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
